--BAI2_A

CREATE VIEW ThongTinPhong
AS
	SELECT HONV, TENNV, TENPHG, DIADIEM
	FROM NHANVIEN, DIADIEM_PHG, PHONGBAN

--BAI2_B

CREATE VIEW NhanVienLuongTuoi
AS
	SELECT TENNV, LUONG, DATEDIFF(YEAR,NGSINH, GETDATE()) AS TUOI
	FROM NHANVIEN


--BAI2_C

CREATE VIEW PhongBanDongNhat
AS
	SELECT PHONGBAN.TENPHG, NHANVIEN.HONV + ' ' +NHANVIEN.TENLOT + ' ' +NHANVIEN.TENNV AS 'TenTruongPhong'
	FROM PHONGBAN INNER JOIN NHANVIEN
	ON PHONGBAN.TRPHG = NHANVIEN.MANV
	WHERE MAPHG IN (
		SELECT PHG FROM NHANVIEN
		GROUP BY PHG
		HAVING COUNT(MANV) = 
			(SELECT TOP 1 COUNT(MANV) AS NVCOUNT FROM NHANVIEN
				GROUP BY PHG
				ORDER BY NVCOUNT DESC)
	)