
--BAI1_A

CREATE FUNCTION fAge(@MaNV nvarchar(9))
	RETURNS INT
AS
BEGIN
	RETURN(SELECT DATEDIFF(YEAR, NGSINH, GETDATE()) + 1
			FROM NHANVIEN 
			WHERE MANV = @MaNV)
END;

--BAI1_B

CREATE FUNCTION fTongDEAN(@MaNV nvarchar(9))
	RETURNS INT
AS
BEGIN
	RETURN(SELECT COUNT(MADA)
			FROM PHANCONG 
			WHERE MA_NVIEN = @MaNV)
END;

--BAI1_C

CREATE FUNCTION fNV_GioiTinh(@phai nvarchar(3))
	RETURNS INT
AS
BEGIN
	RETURN(SELECT COUNT(MaNV)
			FROM NHANVIEN 
			WHERE PHAI = @phai)
END;

--BAI1_D

CREATE FUNCTION fNV_LuongTB(@TenPhong nvarchar(30))
	RETURNS INT
AS
BEGIN
	RETURN(SELECT AVG(NHANVIEN.LUONG)
			FROM PHONGBAN INNER JOIN NHANVIEN 
			ON PHONGBAN.MAPHG = NHANVIEN.PHG
			WHERE TENPHG LIKE '%' +@TenPhong+ '%')
END;

SELECT HONV, TENLOT, TENNV 
	FROM NHANVIEN INNER JOIN PHONGBAN
	ON NHANVIEN.PHG = PHONGBAN.MAPHG 
	WHERE LUONG > [dbo].[fNV_LuongTB] (N'Quản lý') and TENPHG LIKE N'%Quản Lý%'
SELECT * FROM PHONGBAN;



--BAI1_E

CREATE FUNCTION f_ThongtinDeAn(@MaPhg INT)
	RETURNS @List TABLE (TenPhong NVARCHAR(15), TenTruongPhong NVARCHAR(30), SLDeAn INT)
AS
BEGIN
	INSERT INTO @List
		SELECT PHONGBAN.TENPHG, NHANVIEN.HONV + ' ' + NHANVIEN.TENLOT+ ' ' + NHANVIEN.TENNV,
			(SELECT COUNT(DEAN.MADA) FROM DEAN
			 WHERE DEAN.PHONG = PHONGBAN.MAPHG)
			 FROM PHONGBAN INNER JOIN NHANVIEN 
			 ON PHONGBAN.MAPHG = NHANVIEN.PHG
	RETURN
END

SELECT * FROM f_ThongtinDeAn(1)
